version: "3.4"

services:
  identity-api:
    environment:
      - IdentityServer__SpaClientHost=http://${FRONTEND_DNS_OR_IP}
      - IdentityServer__Issuer=http://identity.${SITE_HOST}
    labels:
      # Cors Middleware
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*,X-Requested-With,X-SignalR-User-Agent"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
      - "traefik.enable=true"
      - "traefik.http.routers.identity-api.rule=Host(`identity.${SITE_HOST}`)"
      - "traefik.http.routers.identity-api.entrypoints=web"
      - "traefik.http.routers.identity-api.middlewares=cors@docker"
      - "traefik.http.routers.identity-api.tls=false"

  strive:
    labels:
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=http://timetock.com,http://localhost:55103"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*,X-Requested-With,X-SignalR-User-Agent"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${SITE_HOST}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.strive.loadbalancer.healthcheck.path=/health/ready"
      - "traefik.http.routers.api.middlewares=cors@docker"
      - "traefik.http.routers.api.tls=false"
    environment:
      - SFU__UrlTemplate=http://sfu.${SITE_HOST}/{0}
      - Authentication__NoSslRequired=true
      - Authentication__Issuer=http://identity.${SITE_HOST}

  webspa:
    labels:
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*,X-Requested-With,X-SignalR-User-Agent"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
      - "traefik.enable=true"
      - "traefik.http.routers.spa.rule=Host(`${FRONTEND_DNS_OR_IP}`)"
      - "traefik.http.routers.spa.entrypoints=web"
      - "traefik.http.services.webspa.loadbalancer.healthcheck.path=/health"
      - "traefik.http.routers.spa.tls=false"
    environment:
      - App__IdentityUrl=http://identity.${SITE_HOST}
      - App__FrontendUrl=http://${FRONTEND_DNS_OR_IP}
      - App__ConferenceUrl=http://api.${SITE_HOST}/
      - App__SignalrHubUrl=http://api.${SITE_HOST}/signalr
      - App__EquipmentSignalrHubUrl=http://api.${SITE_HOST}/equipment-signalr

  sfu:
    labels:
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*,X-Requested-With,X-SignalR-User-Agent"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sfu.rule=Host(`sfu.${SITE_HOST}`)"
      - "traefik.http.routers.sfu.entrypoints=web"
      - "traefik.http.services.sfu.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.sfu.loadbalancer.healthcheck.port=9000"
      - "traefik.http.services.sfu.loadbalancer.server.port=3000"
      - "traefik.http.routers.sfu.middlewares=cors@docker"
      - "traefik.http.routers.sfu.tls=false"
