version: "3.4"

services:
  sfu:
    build:
      args:
        - MEDIASOUP_MIN_PORT=2000
        - MEDIASOUP_MAX_PORT=20000
    ports:
      - "3000:3000"
      - "2000-20000:2000-20000/udp"
      - "2000-20000:2000-20000/tcp"
      - "9000:9000"
    environment:
      - DEBUG=strive-mediasoup**
  
  traefik:
    image: "traefik:v2.4"
    command:
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"

networks:
  traefik-net:
      driver: overlay
      ipam:
          driver: default
