version: "3.4"

services:
  sfu:
    build:
      args:
        - MEDIASOUP_MIN_PORT=2000
        - MEDIASOUP_MAX_PORT=2020
    ports:
      - "3000:3000"
      - "2000-2020:2000-2020/udp"
      - "2000-2020:2000-2020/tcp"
      - "9000:9000"
    environment:
      - DEBUG=strive-mediasoup**
  
  traefik:
    image: "traefik:v2.4"
    command:
      - "--entrypoints.web.http.redirections.entryPoint.to=web"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=http"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

    ports:
      - "80:80"
      # - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik.yml:/traefik.yml:ro"

networks:
  traefik-net:
      driver: overlay
      ipam:
          driver: default