version: "3.4"

services:
  sfu:
    build:
      args:
        - MEDIASOUP_MIN_PORT=40000
        - MEDIASOUP_MAX_PORT=49999
    ports:
      - "3000:3000"
      - "40000-49999:40000-49999/udp"
      - "40000-49999:40000-49999/tcp"
      - "9000:9000"
    environment:
      - DEBUG=strive-mediasoup**
  
  traefik:
    image: "traefik:v2.4"
    command:
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"

networks:
  traefik-net:
      driver: overlay
      ipam:
          driver: default
